name = 'Rob Johnston Theme'
license = 'MIT'
licenselink = 'https://github.com/robjohnston/robjohnston.github.io/blob/main/LICENSE'
description = 'Custom Hugo theme for Rob Johnston blog, based on hugo-theme-tailwind with enhanced UI features'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/robjohnston/robjohnston.github.io'

# Original theme attribution
# Based on hugo-theme-tailwind by Xiaoliang Wang (https://github.com/tomowang/hugo-theme-tailwind)

version = "1.0.0"

# Taxonomy terms
tags = ['blog', 'tailwindcss', 'responsive', 'multilingual', 'dark', 'personal', 'scientific', 'technical']
features = [
  "responsive",
  "dark mode",
  "table of contents",
  "katex",
  "tabler icons",
  "multilingual",
  "search",
  "image process",
  "json-ld",
  "pwa",
  "series navigation",
  "enhanced cards",
]


# If the theme has a single author
[author]
  name = 'Rob Johnston'
  homepage = 'https://robjohnston.github.io'
